[package]
name = "citation-graph"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
slotmap = "1.0.7"
tokio = { version = "1.38.0", features = ["macros", "rt", "rt-multi-thread"] }
